import React, { useRef, useState, useEffect } from 'react';
import { motion, useScroll, useTransform, AnimatePresence } from 'framer-motion';
import Magnetic from '../components/Magnetic';
import DownloadCV from '../components/DownloadCV';

const Home = () => {
  const containerRef = useRef(null);
  
  const [isMuted, setIsMuted] = useState(true);
  const [isVideoLoaded, setIsVideoLoaded] = useState(false);
  const videoRef = useRef(null);

  const toggleMute = () => {
    if (videoRef.current) {
      const nextMuted = !isMuted;
      videoRef.current.muted = nextMuted;
      setIsMuted(nextMuted);
      
      // Some browsers require explicit play() after unmuting
      if (!nextMuted) {
        videoRef.current.play().catch(err => console.error("Playback prevented:", err));
      }
    }
  };

  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start start", "end start"]
  });
  
  const y = useTransform(scrollYProgress, [0, 1], ["0vh", "40vh"]);

  const [typeText, setTypeText] = useState('');
  const fullText = "Software Engineer";
  
  useEffect(() => {
    let i = 0;
    const typing = setInterval(() => {
      if (i < fullText.length) {
        setTypeText(fullText.slice(0, i + 1));
        i++;
      } else {
        clearInterval(typing);
      }
    }, 150);
    return () => clearInterval(typing);
  }, []);

  return (
    <section id="home" ref={containerRef} className="scroll-wrap visible" style={{ minHeight: '100vh', position: 'relative', overflow: 'hidden' }}>
      <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', display: 'flex', alignItems: 'center', pointerEvents: 'none' }}>
        
        {/* VIDEO CONTAINER ON THE RIGHT */}
        <div style={{ position: 'absolute', top: 0, right: '5%', width: '40%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', pointerEvents: 'none', zIndex: 1 }}>
          {/* Intense Glow Behind Video */}
          <motion.div 
            initial={{ opacity: 0, scale: 0.5 }}
            animate={{ opacity: 0.5, scale: 1 }}
            transition={{ duration: 1.5, ease: "easeOut" }}
            style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', width: '500px', height: '500px', background: 'var(--accent)', filter: 'blur(120px)', borderRadius: '50%' }} 
          />
          {/* Video element with smooth edge blending */}
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1.5, delay: 0.4, ease: "easeOut" }}
            style={{
              position: 'relative',
              width: '100%',
              maxWidth: '500px',
              aspectRatio: '3/4',
              /* Smoothly fade the edges of the video into the background */
              WebkitMaskImage: 'radial-gradient(ellipse at center, black 40%, transparent 80%)',
              maskImage: 'radial-gradient(ellipse at center, black 40%, transparent 80%)',
              pointerEvents: 'auto'
            }}
          >
            <video 
              ref={videoRef}
              autoPlay 
              loop 
              muted={isMuted}
              playsInline
              onLoadedData={() => setIsVideoLoaded(true)}
              style={{ 
                width: '100%', 
                height: '100%', 
                objectFit: 'cover'
              }}
            >
              {/* This WebM file will be generated by the AI script in the background */}
              <source src="/assets/videos/hero_video_nobg.webm" type="video/webm" />
              {/* Fallback to original MP4 while we wait for AI processing */}
              <source src="/assets/videos/hero_video.mp4" type="video/mp4" />
            </video>

            <AnimatePresence>
              {!isVideoLoaded && (
                <motion.div
                  initial={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  transition={{ duration: 0.8 }}
                  className="shimmer"
                  style={{
                    position: 'absolute',
                    inset: 0,
                    borderRadius: '16px',
                    zIndex: 5
                  }}
                />
              )}
            </AnimatePresence>

            {/* Sound Toggle Button */}
            <button 
              onClick={toggleMute}
              className="glass-pill link-hover"
              style={{
                position: 'absolute',
                bottom: '20px',
                right: '20px',
                background: 'rgba(0, 0, 0, 0.5)',
                border: '1px solid rgba(0, 242, 254, 0.3)',
                color: 'var(--accent)',
                width: '40px',
                height: '40px',
                borderRadius: '50%',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                cursor: 'pointer',
                fontSize: '1.2rem',
                zIndex: 20
              }}
            >
              {isMuted ? '🔇' : '🔊'}
            </button>
          </motion.div>
        </div>

        <motion.div style={{ padding: '0 var(--pad-x)', width: '100%', y, pointerEvents: 'auto', display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
          
          {/* MASSIVE TYPOGRAPHY */}
          <div style={{ position: 'relative', zIndex: 10, display: 'flex', flexDirection: 'column', alignItems: 'flex-start', maxWidth: '60%' }}>
            <motion.h1 
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}
              style={{ 
                fontFamily: 'var(--font-display)', 
                fontSize: 'clamp(3rem, 8vw, 6rem)', 
                fontWeight: 900, 
                lineHeight: 0.85, 
                letterSpacing: '-0.04em', 
                color: 'var(--fg)',
                margin: 0,
                textTransform: 'uppercase',
                textShadow: '0 0 40px rgba(0, 242, 254, 0.2)'
              }}
            >
              CRAFTING
            </motion.h1>
            <motion.h1 
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 1, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
              style={{ 
                fontFamily: 'var(--font-display)', 
                fontSize: 'clamp(3rem, 8vw, 6rem)', 
                fontWeight: 900, 
                lineHeight: 0.85, 
                letterSpacing: '-0.04em', 
                margin: 0,
                textTransform: 'uppercase',
                color: 'transparent',
                WebkitTextStroke: '3px var(--accent)',
                fontStyle: 'italic',
                marginLeft: '5vw',
                filter: 'drop-shadow(0 0 20px rgba(0, 242, 254, 0.4))'
              }}
            >
              DIGITAL
            </motion.h1>
            <motion.h1 
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 1, delay: 0.2, ease: [0.16, 1, 0.3, 1] }}
              style={{ 
                fontFamily: 'var(--font-display)', 
                fontSize: 'clamp(3rem, 8vw, 6rem)', 
                fontWeight: 900, 
                lineHeight: 0.85, 
                letterSpacing: '-0.04em', 
                color: 'var(--fg)',
                margin: 0,
                textTransform: 'uppercase',
                textShadow: '0 0 40px rgba(0, 242, 254, 0.2)'
              }}
            >
              REALITIES
            </motion.h1>
          </div>

          {/* SUBTEXT */}
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 1, delay: 0.8 }}
            style={{ 
              fontFamily: 'var(--font-body)', 
              fontSize: 'clamp(1rem, 1.5vw, 1.2rem)', 
              color: 'var(--fg-dim)', 
              maxWidth: '800px', 
              lineHeight: 1.6,
              marginTop: '3rem',
              marginBottom: '2rem',
              zIndex: 10
            }}
          >
            Hi, I'm Anusha. Translating complex logic into immersive digital experiences.
          </motion.p>

          {/* CURRENTLY STATUS */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 1, delay: 1 }}
            style={{ 
              fontFamily: 'var(--font-mono)', 
              fontSize: '0.85rem', 
              color: 'var(--fg-dim)', 
              textTransform: 'uppercase', 
              letterSpacing: '0.1em',
              marginBottom: '4rem',
              zIndex: 10,
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem'
            }}
          >
            CURRENTLY: <span style={{ color: 'var(--fg)', fontWeight: 600 }}>{typeText}</span>
            <motion.div 
              animate={{ opacity: [1, 0] }} 
              transition={{ repeat: Infinity, duration: 0.8, ease: "linear" }}
              style={{ width: '8px', height: '16px', background: 'var(--accent)' }}
            />
          </motion.div>

          {/* BUTTONS */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 1.2 }}
            style={{ display: 'flex', gap: '1.5rem', alignItems: 'center', zIndex: 10, flexWrap: 'wrap' }}
          >
            <Magnetic>
              <button 
                onClick={() => {
                  const el = document.getElementById('works');
                  if (el) el.scrollIntoView({ behavior: 'smooth' });
                }}
                className="link-hover glass-pill"
                style={{
                  background: 'var(--fg)',
                  color: 'var(--bg)',
                  fontFamily: 'var(--font-mono)',
                  fontSize: '0.8rem',
                  fontWeight: 700,
                  textTransform: 'uppercase',
                  letterSpacing: '0.1em',
                  padding: '1rem 2rem',
                  border: 'none',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.8rem'
                }}
              >
                EXPLORE INDEX &rarr;
              </button>
            </Magnetic>
            
            <Magnetic>
              <DownloadCV />
            </Magnetic>
          </motion.div>

        </motion.div>
      </div>
    </section>
  );
};

export default Home;
